# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd

argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.1
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
